runtime: php55
api_version: 1

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /back/(.+\.php)$
  script: \1

- url: /(.+?)\.php
  script: main.php

- url: /
  script: main.php